version: "3"
services: 
  redis:
    image: redis
    ports: 
        - "6379:6379"
    container_name: redisdb
    restart: always
    volumes:
      - /mnt/redisdb:/data
    networks:
      - mobilephone
  mongo:
    image: mongo
    ports: 
        - "27017:27017"
    container_name: mongodb
    restart: always
    volumes:
      - /mnt/mongodbData:/data/db
    networks:
      - mobilephone
  mysql:
    image: mysql
    ports: 
        - "3306:3306"
    container_name: mysqldb
    restart: always
    volumes:
      - /mnt/mysqldata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD:123456
    networks:
      - mobilephone
  adb:
    image: sorccu/adb
    container_name: adbd
    restart: always
    ports:
      - "5037:5037"
    volumes:
      - /dev/bus/usb:/dev/bus/usb
    networks:
      - mobilephone
    privileged: true
  rethinkdb:
    image: rethinkdb:2.3
    ports:
      - "8080:8080"
      - "28015:28015"
      - "29015:29015"
    restart: always
    networks:
      - mobilephone
    volumes:
      - "/mnt/rethinkdb:/data"
    command: "rethinkdb --bind all --cache-size 2048"
  stf-local:
    image: openstf/stf
    depends_on:
      - rethinkdb
      - adbd
    ports:
      - "7100:7100"
      - "7110:7110"
      - "7120:7120"
      - "7400-7500:7400-7500"
    networks:
      - mobilephone
    restart: always
    command: stf local --public-ip 192.168.10.176 --provider-min-port 7400 --provider-max-port 7500 --adb-host adbd
  nodejsqueue:
    image: tymx/nodejsqueue:v1
    container_name: nodejsqueue
    ports: 
        - "3000:3000"
    restart: always
    volumes:
      - /home/tymx/Documents/DockerContainer/nodejsqueue:/usr/local/nodejsqueue
      - /home/tymx/Documents/DockerContainer/nodejsqueue/uploads:/usr/local/nodejsqueue/redisService/uploads
    networks:
      - mobilephone
    depends_on:
      - redis
      - mongo
  anyproxy:
    build: anyproxy4_x/
    restart: always
    ports: 
      - "7001:8001"
      - "7002:8002"
      - "7013:8013"
    expose:
      - "8001"
      - "8002"
      - "8013"
    volumes:
      - /home/tymx/Documents/DockerContainer/anyproxy4_x:/usr/local/anyproxy
    command: anyproxy --intercept --rule /usr/local/anyproxy/rulefiles/rule.js
    depends_on:
      - nodejsqueue
    networks:
      - mobilephone
  ecologicalmonitor:
    build: monkeyrunner/
    restart: always
    volumes:
      - /home/tymx/Documents/DockerContainer/monkeyrunner/ecological:/usr/local/monkeyrunner/ecological
    depends_on:
      - redis
      - mongo
    networks:
      - mobilephone
  imagedownload:
    build: ECOServer/downloadServer/
    restart: always
    volumes:
      - /home/tymx/Documents/DockerContainer/ECOServer:/usr/local/imagedownload
      - /home/tymx/Documents/download:/usr/local/imagedownload/downloadServer/files
    depends_on:
      - redis
      - mongo
    networks:
      - mobilephone
  ecoserver:
    build: ECOServer/
    restart: always
    volumes:
      - /home/tymx/Documents/DockerContainer/ECOServer:/usr/local/ECOServer
    depends_on:
      - redis
      - mongo
      - mysql
    networks:
      - mobilephone
  ocrserver:
    build: ECOServer/
    restart: always
    volumes:
      - /home/tymx/Documents/DockerContainer/ECOServer:/usr/local/ECOServer
    command: python /usr/local/ECOServer/screencap_match_main.py
    depends_on:
      - redis
      - mongo
      - mysql
    networks:
      - mobilephone
  dockerui:
    image: abh1nav/dockerui:latest
    restart: always
    volumes:
      - /var/run/docker.sock:/docker.sock
    ports: 
      - "19000:9000"
    privileged: true
    depends_on:
      - redis
      - mongo
      - mysql
    networks:
      - mobilephone


networks:
  mobilephone:
    driver: bridge

