version: "3"
services: 
  adbd:
    image: sorccu/adb
    container_name: adbd
    restart: always
    ports:
      - "5037:5037"
    volumes:
      - /dev/bus/usb:/dev/bus/usb
    privileged: true
    network_mode: "host"
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://192.168.10.177:12201"
        tag: adbd
  rethinkdb:
    image: rethinkdb
    restart: always
    ports:
      - "8080:8080"
      - "28015:28015"
      - "29015:29015"
    volumes:
      - "/mnt/db/rethinkdb:/data"
    network_mode: "host"
    command: "rethinkdb --bind all --cache-size 2048"
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://192.168.10.177:12201"
        tag: rethinkdb
  stf-local:
    image: openstf/stf
    restart: always
    depends_on:
      - rethinkdb
      - adbd
    ports:
      - "7100:7100"
      - "7110:7110"
      - "7120:7120"
      - "7400-7500:7400-7500"
    network_mode: "host"
    command: stf local --public-ip 192.168.10.177
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://192.168.10.177:12201"
        tag: stf
  redis:
    image: redis
    restart: always
    ports: 
        - "6379:6379"
    container_name: redisdb
    volumes:
      - /mnt/db/redisdb:/data
    networks:
      - mobilephone_release
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://192.168.10.177:12201"
        tag: redis
  mongo:
    image: mongo
    restart: always
    ports: 
        - "27017:27017"
    container_name: mongodb
    volumes:
      - /mnt/db/mongodbData:/data/db
    networks:
      - mobilephone_release
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://192.168.10.177:12201"
        tag: mongo
  mysql:
    image: mysql
    restart: always
    ports: 
        - "3306:3306"
    container_name: mysqldb
    volumes:
      - /mnt/db/mysqldata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    networks:
      - mobilephone_release
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://192.168.10.177:12201"
        tag: mysql
  nodejsqueue:
    build: nodejsqueue/
    container_name: nodejsqueue
    restart: always
    ports: 
        - "3000:3000"
    volumes:
      - /home/tymx/Documents/DockerContainer/nodejsqueue:/usr/local/nodejsqueue
      - /mnt/upload_files:/usr/local/nodejsqueue/redisService/uploads
      - /mnt/analysis_media:/mnt/analysis_media
    networks:
      - mobilephone_release
    depends_on:
      - redis
      - mongo
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://192.168.10.177:12201"
        tag: nodejsqueue
  mitmproxy:
    build: mitmproxy/
    restart: always
    ports: 
      - "8088:8080"
      - "8081:8081"
    expose:
      - "8080"
      - "8081"
    volumes:
      - /home/tymx/Documents/DockerContainer/mitmproxy/crt:/root/.mitmproxy
      - /home/tymx/Documents/DockerContainer/ECOServer/mitmproxyServer:/tmp/script
    command: mitmweb --web-iface 0.0.0.0 --ssl-insecure -s /tmp/script/AddRule.py
    depends_on:
      - redis
    networks:
      - mobilephone_release
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://192.168.10.177:12201"
        tag: mitmproxy
  anyproxy:
    build: anyproxy4_x/
    restart: always
    ports: 
      - "7001:8001"
      - "7002:8002"
      - "7013:8013"
    expose:
      - "8001"
      - "8002"
      - "8013"
    volumes:
      - /home/tymx/Documents/DockerContainer/anyproxy4_x:/usr/local/anyproxy
    command: anyproxy --intercept --rule /usr/local/anyproxy/rulefiles/rule.js
    depends_on:
      - nodejsqueue
    networks:
      - mobilephone_release
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://192.168.10.177:12201"
        tag: anyproxy
  ecologicalmonitor:
    build: monkeyrunner/
    restart: always
    volumes:
      - /home/tymx/Documents/DockerContainer/monkeyrunner/ecological:/usr/local/monkeyrunner/ecological
      - /mnt/db/logs:/usr/local/monkeyrunner/ecological/logs
    depends_on:
      - redis
      - mongo
      - adbd
    networks:
      - mobilephone_release
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://192.168.10.177:12201"
        tag: ecologicalmonitor
  ecoserver:
    build: ECOServer/
    restart: always
    volumes:
      - /home/tymx/Documents/DockerContainer/ECOServer:/usr/local/ECOServer
      - /mnt/db/logs:/usr/local/ECOServer/logs
    depends_on:
      - redis
      - mongo
      - mysql
    networks:
      - mobilephone_release
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://192.168.10.177:12201"
        tag: ecoserver
  ocrserver:
    build: ECOServer/
    restart: always
    volumes:
      - /home/tymx/Documents/DockerContainer/ECOServer:/usr/local/ECOServer
      - /mnt/db/logs:/usr/local/ECOServer/logs
    command: python /usr/local/ECOServer/screencap_match_main.py
    depends_on:
      - redis
      - mongo
      - mysql
    networks:
      - mobilephone_release
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://192.168.10.177:12201"
        tag: ocrserver
  imagedownload:
    build: ECOServer/
    restart: always
    volumes:
      - /home/tymx/Documents/DockerContainer/ECOServer:/usr/local/ECOServer
      - /mnt/download_media:/usr/local/ECOServer/mediaDownloadServer/files
      - /mnt/db/logs:/usr/local/ECOServer/logs
    command: python /usr/local/ECOServer/media_download_server.py
    depends_on:
      - redis
      - mongo
    networks:
      - mobilephone_release
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://192.168.10.177:12201"
        tag: imagedownload
  dockerui:
    image: abh1nav/dockerui:latest
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports: 
      - "19000:9000"
    privileged: true
    depends_on:
      - redis
      - mongo
      - mysql
    networks:
      - mobilephone_release
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://192.168.10.177:12201"
        tag: dockerui


networks:
  mobilephone_release:
    driver: bridge

