version: "3"
services: 
  redis:
    image: redis
    ports: 
        - "6379:6379"
    container_name: redisdb
    restart: always
    volumes:
      - /Users/lizhengqing/Documents/redisdb:/data
    networks:
      - mobilephone
  mongo:
    image: mongo
    ports: 
        - "27017:27017"
    container_name: mongodb
    restart: always
    volumes:
      - /Users/lizhengqing/Documents/mongodbData:/data/db
    networks:
      - mobilephone
  mysql:
    image: mysql
    ports: 
        - "3306:3306"
    container_name: mysqldb
    restart: always
    volumes:
      - /Users/lizhengqing/Documents/mysqldata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD:123456
    networks:
      - mobilephone
  adb:
    image: sorccu/adb
    container_name: adbd
    restart: always
    volumes:
      - /etc/bus/usb:/dev/bus/usb
    networks:
      - mobilephone
    privileged: true
  nodejsqueue:
    image: tymx/nodejsqueue:v1
    container_name: nodejsqueue
    ports: 
        - "3000:3000"
    restart: always
    volumes:
      - /Users/lizhengqing/Documents/DockerContainer/nodejsqueue:/usr/local/nodejsqueue
      - /Users/lizhengqing/Documents/DockerContainer/nodejsqueue/uploads:/usr/local/nodejsqueue/redisService/uploads
    networks:
      - mobilephone
    depends_on:
      - redis
      - mongo
  anyproxy:
    build: anyproxy4_x/
    restart: always
    ports: 
      - "7001:8001"
      - "7002:8002"
      - "7013:8013"
    expose:
      - "8001"
      - "8002"
      - "8013"
    volumes:
      - /Users/lizhengqing/Documents/DockerContainer/anyproxy4_x:/usr/local/anyproxy
    command: anyproxy --intercept --rule /usr/local/anyproxy/rulefiles/rule.js
    depends_on:
      - nodejsqueue
    networks:
      - mobilephone
  ecologicalmonitor:
    build: monkeyrunner/
    restart: always
    volumes:
      - /Users/lizhengqing/Documents/DockerContainer/monkeyrunner/ecological:/usr/local/monkeyrunner/ecological
    depends_on:
      - redis
      - mongo
    networks:
      - mobilephone
  imagedownload:
    build: ECOServer/downloadServer/
    restart: always
    volumes:
      - /Users/lizhengqing/Documents/DockerContainer/ECOServer:/usr/local/imagedownload
      - /Users/lizhengqing/Documents/download:/usr/local/imagedownload/downloadServer/files
    depends_on:
      - redis
      - mongo
    networks:
      - mobilephone
  ecoserver:
    build: ECOServer/
    restart: always
    volumes:
      - /Users/lizhengqing/Documents/DockerContainer/ECOServer:/usr/local/ECOServer
    depends_on:
      - redis
      - mongo
      - mysql
    networks:
      - mobilephone
  ocrserver:
    build: ECOServer/
    restart: always
    volumes:
      - /Users/lizhengqing/Documents/DockerContainer/ECOServer:/usr/local/ECOServer
    command: python /usr/local/ECOServer/screencap_match_main.py
    depends_on:
      - redis
      - mongo
      - mysql
    networks:
      - mobilephone
  dockerui:
    image: abh1nav/dockerui:latest
    restart: always
    volumes:
      - /var/run/docker.sock:/docker.sock
    ports: 
      - "19000:9000"
    privileged: true
    depends_on:
      - redis
      - mongo
      - mysql
    networks:
      - mobilephone
networks:
  mobilephone:
    driver: bridge

