version: "3"
services: 
  adbd:
    image: sorccu/adb
    container_name: adbd
    restart: always
    ports:
      - "5037:5037"
    volumes:
      - /dev/bus/usb:/dev/bus/usb
    privileged: true
    network_mode: "host"
  rethinkdb:
    image: rethinkdb
    ports:
      - "8080:8080"
      - "28015:28015"
      - "29015:29015"
    restart: always
    volumes:
      - "/mnt/rethinkdb:/data"
    network_mode: "host"
    command: "rethinkdb --bind all --cache-size 2048"
  stf-local:
    image: openstf/stf
    depends_on:
      - rethinkdb
      - adbd
    ports:
      - "7100:7100"
      - "7110:7110"
      - "7120:7120"
      - "7400-7500:7400-7500"
    network_mode: "host"
    restart: always
    command: stf local --public-ip 192.168.10.176 --provider-min-port 7400 --provider-max-port 7500 --adb-host adbd
  


networks:
  mobilephone:
    driver: bridge

