version: "3"
services: 
  mongo:
    image: mongo
    restart: always
    ports: 
        - "27017:27017"
    container_name: mongodb
    volumes:
      - /mnt/mongodbData:/data/db
  mysql:
    image: mysql
    restart: always
    ports: 
        - "3306:3306"
    container_name: mysqldb
    volumes:
      - /mnt/mysqldata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
  dockerui:
    image: abh1nav/dockerui:latest
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports: 
      - "19000:9000"
    privileged: true
    depends_on:
      - mongo
      - mysql

