FROM node:6.9.2
MAINTAINER lichien@qq.com
EXPOSE 3000

RUN mkdir /usr/local/nodejsqueue

RUN mkdir /usr/local/nodejsqueue/uploads
RUN mkdir /mnt/analysis_media
#COPY ./ /usr/local/nodejsqueue/

CMD ["node","usr/local/nodejsqueue/redisService/bin/www/"]

