version: "3"
services: 
  redis:
    image: redis
    restart: always
    ports: 
        - "6379:6379"
    container_name: redisdb
    volumes:
      - /mnt/db/redisdb:/data
    networks:
      - mobilephone_release
  mongo:
    image: mongo
    restart: always
    ports: 
        - "27017:27017"
    container_name: mongodb
    volumes:
      - /mnt/db/mongodbData:/data/db
    networks:
      - mobilephone_release
  mysql:
    image: mysql
    restart: always
    ports: 
        - "3306:3306"
    container_name: mysqldb
    volumes:
      - /mnt/db/mysqldata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    networks:
      - mobilephone_release
  dockerui:
    image: abh1nav/dockerui:latest
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports: 
      - "19000:9000"
    privileged: true
    depends_on:
      - redis
      - mongo
      - mysql
    networks:
      - mobilephone_release
networks:
  mobilephone_release:
    driver: bridge